package in.nic.training.entity;
// Generated Jul 6, 2016 5:02:01 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * StudentCourseMapping generated by hbm2java
 */
@Entity
@Table(name = "student_course_mapping", schema = "public")
public class StudentCourseMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int studentCourseMappingId;
	private Courses courses;
	private StudentInfo studentInfo;

	public StudentCourseMapping() {
	}

	public StudentCourseMapping(int studentCourseMappingId, Courses courses, StudentInfo studentInfo) {
		this.studentCourseMappingId = studentCourseMappingId;
		this.courses = courses;
		this.studentInfo = studentInfo;
	}

	@Id
	@SequenceGenerator(name="student_course_mapping_id_seq", sequenceName="student_course_mapping_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="student_course_mapping_id_seq")
	@Column(name = "student_course_mapping_id", unique = true, nullable = false)
	public int getStudentCourseMappingId() {
		return this.studentCourseMappingId;
	}

	public void setStudentCourseMappingId(int studentCourseMappingId) {
		this.studentCourseMappingId = studentCourseMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public StudentInfo getStudentInfo() {
		return this.studentInfo;
	}

	public void setStudentInfo(StudentInfo studentInfo) {
		this.studentInfo = studentInfo;
	}

}
