package in.nic.training.entity;
// Generated Jul 6, 2016 5:02:01 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * StudentSubjectMapping generated by hbm2java
 */
@Entity
@Table(name = "student_subject_mapping", schema = "public")
public class StudentSubjectMapping implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long studentSubjectMappingId;
	private StudentInfo studentInfo;
	private Subjects subjects;

	public StudentSubjectMapping() {
	}

	public StudentSubjectMapping(long studentSubjectMappingId, StudentInfo studentInfo, Subjects subjects) {
		this.studentSubjectMappingId = studentSubjectMappingId;
		this.studentInfo = studentInfo;
		this.subjects = subjects;
	}

	@Id
	@SequenceGenerator(name="student_subject_mapping_id_seq", sequenceName="student_subject_mapping_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="student_subject_mapping_id_seq")
	@Column(name = "student_subject_mapping_id", unique = true, nullable = false)
	public long getStudentSubjectMappingId() {
		return this.studentSubjectMappingId;
	}

	public void setStudentSubjectMappingId(long studentSubjectMappingId) {
		this.studentSubjectMappingId = studentSubjectMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false)
	public StudentInfo getStudentInfo() {
		return this.studentInfo;
	}

	public void setStudentInfo(StudentInfo studentInfo) {
		this.studentInfo = studentInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_id", nullable = false)
	public Subjects getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Subjects subjects) {
		this.subjects = subjects;
	}

}
