package in.nic.training.entity;
// Generated Jul 6, 2016 5:02:01 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name = "subjects", schema = "public")
public class Subjects implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String subjectId;
	private String subjectCode;
	private String subjectName;
	private Set<StudentSubjectMapping> studentSubjectMappings = new HashSet<>(0);

	public Subjects() {
	}

	public Subjects(String subjectId, String subjectCode, String subjectName) {
		this.subjectId = subjectId;
		this.subjectCode = subjectCode;
		this.subjectName = subjectName;
	}

	public Subjects(String subjectId, String subjectCode, String subjectName, Set<StudentSubjectMapping> studentSubjectMappings) {
		this.subjectId = subjectId;
		this.subjectCode = subjectCode;
		this.subjectName = subjectName;
		this.studentSubjectMappings = studentSubjectMappings;
	}

	@Id
	@GenericGenerator(name = "subject_id_seq", strategy = "in.nic.training.util.SubjectIdGenerator")
	@GeneratedValue(generator = "subject_id_seq")
	@Column(name = "subject_id", unique = true, nullable = false, length = 7)
	public String getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId;
	}

	@Column(name = "subject_code", nullable = false, length = 5)
	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	@Column(name = "subject_name", nullable = false, length = 15)
	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subjects")
	public Set<StudentSubjectMapping> getStudentSubjectMappings() {
		return this.studentSubjectMappings;
	}

	public void setStudentSubjectMappings(Set<StudentSubjectMapping> studentSubjectMappings) {
		this.studentSubjectMappings = studentSubjectMappings;
	}

}
